In [6]:
! unzip '/archive (2).zip'

Archive:  /archive (2).zip
  inflating: ObesityDataSet.csv

In [7]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/ObesityDataSet.csv')

In [8]:
df['Gender']= df['Gender'].replace({'Male':0, 'Female':1})
df['FAVC']=df['FAVC'].replace({'yes':1,'no':0})
df['family_history_with_overweight']= df['family_history_with_overweight'].replace({'yes':1, 'no':0})

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['CAEC']= le.fit_transform(df['CAEC'])
df['SMOKE']=le.fit_transform(df['SMOKE'])
df['SCC']=le.fit_transform(df['SCC'])
df['CALC']=le.fit_transform(df['CALC'])
pd.get_dummies(df['MTRANS'])
df['MTRANS']=le.fit_transform(df['MTRANS'])
df['NObeyesdad']=le.fit_transform(df['NObeyesdad'])

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
x=df.drop('NObeyesdad',axis=1)
y=df['NObeyesdad']

In [13]:
x

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,1,21.000000,1.620000,64.000000,1,0,2.0,3.0,2,0,2.000000,0,0.000000,1.000000,3,3
1,1,21.000000,1.520000,56.000000,1,0,3.0,3.0,2,1,3.000000,1,3.000000,0.000000,2,3
2,0,23.000000,1.800000,77.000000,1,0,2.0,3.0,2,0,2.000000,0,2.000000,1.000000,1,3
3,0,27.000000,1.800000,87.000000,0,0,3.0,3.0,2,0,2.000000,0,2.000000,0.000000,1,4
4,0,22.000000,1.780000,89.800000,0,0,2.0,1.0,2,0,2.000000,0,0.000000,0.000000,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,1,20.976842,1.710730,131.408528,1,1,3.0,3.0,2,0,1.728139,0,1.676269,0.906247,2,3
2107,1,21.982942,1.748584,133.742943,1,1,3.0,3.0,2,0,2.005130,0,1.341390,0.599270,2,3
2108,1,22.524036,1.752206,133.689352,1,1,3.0,3.0,2,0,2.054193,0,1.414209,0.646288,2,3
2109,1,24.361936,1.739450,133.346641,1,1,3.0,3.0,2,0,2.852339,0,1.139107,0.586035,2,3
2110,1,23.664709,1.738836,133.472641,1,1,3.0,3.0,2,0,2.863513,0,1.026452,0.714137,2,3

In [14]:
y

0       1
1       1
2       1
3       5
4       6
       ..
2106    4
2107    4
2108    4
2109    4
2110    4
Name: NObeyesdad, Length: 2111, dtype: int64

In [15]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=12)

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [17]:
xtrain

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
2009,1,26.000000,1.610225,104.936381,1,1,3.000000,3.000000,2,0,1.322004,0,0.000000,0.539876,2,3
929,0,21.929387,1.698049,75.000000,1,1,2.000000,3.000000,2,0,2.763573,0,1.502711,0.127879,2,3
861,1,21.832995,1.580964,65.363941,0,1,2.021446,3.000000,2,0,1.077917,0,0.523847,0.808599,2,3
1837,1,20.941943,1.812963,138.730619,1,1,3.000000,3.000000,2,0,2.641489,0,0.481555,0.735201,2,3
1312,0,31.641081,1.676595,89.993812,1,1,2.934671,2.119682,2,0,2.041462,0,0.578074,0.000000,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,1,26.000000,1.624950,111.004920,1,1,3.000000,3.000000,2,0,2.704315,0,0.000000,0.322666,2,3
1283,1,30.163408,1.533364,78.030383,1,1,2.028225,1.923607,2,0,1.798917,0,0.000000,0.000000,3,3
1414,1,38.445148,1.556028,77.684229,1,1,2.000000,3.000000,2,0,1.440629,0,0.000000,0.000000,2,0
1691,0,30.722801,1.779325,120.751656,1,1,2.519592,3.000000,2,0,2.229145,0,0.350717,1.140348,2,0
1867,1,26.000000,1.624390,110.008636,1,1,3.000000,3.000000,2,0,2.507461,0,0.000000,0.368472,2,3

In [27]:
dt= DecisionTreeClassifier()
rf=RandomForestClassifier()

In [28]:
dt.fit(xtrain,ytrain)
rf.fit(xtrain,ytrain)

RandomForestClassifier()

In [29]:
ypred=dt.predict(xtest)
yrandompredict=rf.predict(xtest)

In [21]:
ypred

array([0, 1, 4, 5, 6, 6, 0, 1, 5, 3, 2, 6, 0, 4, 3, 5, 1, 4, 3, 0, 3, 0,
       2, 1, 4, 4, 4, 2, 0, 1, 4, 5, 3, 4, 1, 3, 3, 5, 3, 6, 1, 6, 0, 3,
       5, 0, 6, 2, 4, 4, 5, 0, 5, 1, 2, 6, 6, 5, 1, 5, 0, 6, 5, 1, 0, 1,
       4, 2, 1, 3, 4, 0, 4, 2, 3, 5, 6, 2, 0, 1, 0, 5, 4, 0, 3, 2, 2, 3,
       5, 5, 1, 1, 3, 4, 6, 2, 5, 5, 1, 6, 3, 4, 5, 3, 1, 0, 6, 2, 1, 5,
       6, 0, 4, 1, 2, 1, 5, 0, 6, 0, 4, 1, 3, 5, 0, 6, 1, 0, 1, 6, 5, 2,
       0, 1, 1, 1, 5, 6, 2, 1, 3, 1, 1, 0, 2, 1, 4, 6, 5, 2, 6, 0, 3, 0,
       5, 2, 5, 5, 2, 4, 6, 2, 4, 4, 2, 6, 4, 6, 1, 3, 2, 4, 5, 5, 0, 1,
       2, 4, 3, 3, 3, 2, 6, 4, 1, 6, 2, 6, 3, 4, 1, 2, 0, 2, 6, 4, 3, 5,
       6, 4, 2, 0, 0, 0, 4, 4, 6, 0, 1, 5, 5, 4, 1, 1, 3, 3, 6, 2, 2, 1,
       6, 3, 2, 5, 6, 2, 2, 2, 2, 5, 6, 4, 4, 0, 3, 3, 0, 6, 1, 0, 3, 2,
       5, 3, 4, 4, 5, 4, 0, 4, 2, 4, 3, 2, 1, 6, 5, 2, 2, 3, 2, 4, 2, 0,
       5, 0, 4, 1, 5, 2, 2, 2, 3, 4, 5, 5, 3, 3, 0, 5, 2, 2, 5, 0, 0, 5,
       6, 5, 5, 6, 3, 1, 3, 1, 5, 2, 1, 4, 5, 6, 4, 4, 5, 3, 2, 4, 3, 5,
       2, 1, 1, 3, 1, 6, 1, 2, 1, 6, 4, 3, 6, 2, 5, 6, 4, 3, 1, 4, 6, 5,
       0, 6, 2, 2, 1, 4, 6, 2, 2, 0, 5, 0, 5, 4, 0, 5, 2, 4, 4, 2, 1, 0,
       5, 6, 1, 5, 2, 1, 0, 0, 3, 4, 3, 5, 4, 5, 6, 6, 4, 1, 2, 2, 5, 3,
       6, 0, 5, 3, 6, 3, 0, 1, 4, 0, 2, 4, 5, 3, 6, 2, 3, 2, 4, 2, 4, 3,
       4, 5, 0, 2, 2, 6, 6, 1, 0, 5, 0, 4, 3, 6, 3, 4, 3, 5, 1, 6, 5, 6,
       6, 4, 3, 2, 0, 0, 3, 1, 4, 1, 4, 4, 5, 6, 5, 0, 3, 0, 5, 3, 4, 4,
       5, 5, 6, 2, 4, 3, 5, 1, 2, 1, 5, 3, 5, 6, 0, 4, 6, 3, 0, 0, 6, 5,
       0, 6, 3, 1, 5, 6, 3, 5, 6, 2, 0, 1, 3, 1, 3, 4, 5, 4, 2, 6, 3, 6,
       3, 2, 2, 5, 2, 0, 6, 6, 4, 0, 4, 5, 3, 2, 5, 3, 4, 6, 6, 5, 3, 2,
       5, 5, 0, 2, 3, 4, 0, 3, 2, 2, 2, 3, 0, 3, 4, 1, 1, 4, 5, 1, 0, 4,
       1, 2, 4, 3, 2, 3, 4, 0, 2, 2, 2, 4, 3, 2, 4, 4, 5, 6, 5, 4, 5, 6,
       2, 4, 3, 1, 0, 1, 3, 0, 0, 3, 5, 5, 2, 1, 4, 3, 3, 1, 0, 3, 4, 0,
       2, 2, 6, 0, 2, 3, 1, 6, 4, 2, 2, 2, 1, 1, 6, 6, 0, 0, 0, 0, 6, 4,
       0, 3, 5, 4, 0, 1, 3, 3, 2, 5, 2, 1, 4, 3, 2, 0, 3, 2, 5, 6, 2, 1,
       2, 6, 3, 6, 4, 4, 2, 5, 1, 6, 1, 1, 6, 2, 5, 3, 6, 3])

In [30]:
yrandompredict

array([0, 1, 4, 5, 2, 2, 0, 1, 5, 3, 2, 6, 0, 4, 3, 5, 1, 4, 3, 1, 3, 0,
       2, 1, 4, 4, 4, 2, 0, 1, 4, 5, 3, 4, 1, 3, 3, 5, 3, 6, 5, 6, 0, 3,
       5, 0, 6, 2, 4, 4, 6, 0, 5, 1, 2, 6, 6, 5, 5, 5, 1, 2, 5, 1, 0, 1,
       4, 2, 1, 3, 4, 1, 4, 2, 3, 6, 6, 2, 0, 1, 0, 5, 4, 0, 3, 2, 2, 3,
       5, 5, 0, 1, 3, 4, 6, 2, 5, 5, 1, 6, 3, 4, 5, 3, 0, 0, 6, 2, 1, 5,
       3, 0, 4, 1, 2, 5, 1, 0, 6, 0, 4, 1, 3, 6, 0, 6, 5, 0, 1, 6, 5, 2,
       0, 1, 1, 1, 1, 6, 2, 1, 3, 1, 1, 0, 2, 1, 4, 6, 5, 2, 6, 0, 3, 0,
       5, 2, 5, 5, 2, 4, 1, 2, 4, 4, 2, 6, 3, 6, 1, 3, 2, 4, 6, 6, 0, 1,
       2, 4, 3, 3, 3, 2, 6, 4, 1, 6, 2, 6, 3, 4, 1, 2, 0, 2, 6, 4, 3, 5,
       6, 4, 1, 0, 0, 0, 4, 4, 6, 0, 1, 6, 5, 4, 1, 1, 3, 3, 6, 2, 2, 1,
       6, 3, 2, 5, 5, 2, 2, 2, 2, 5, 6, 4, 4, 0, 3, 3, 0, 6, 1, 1, 3, 2,
       6, 3, 4, 4, 5, 4, 0, 4, 2, 4, 3, 2, 1, 6, 6, 2, 2, 3, 2, 4, 2, 0,
       5, 0, 4, 1, 5, 2, 2, 2, 3, 4, 5, 5, 3, 3, 0, 5, 2, 2, 5, 0, 0, 5,
       6, 5, 5, 6, 3, 1, 3, 1, 1, 2, 1, 4, 5, 6, 4, 4, 5, 3, 2, 4, 3, 6,
       2, 1, 5, 3, 0, 2, 1, 2, 1, 6, 4, 3, 6, 2, 5, 6, 4, 3, 1, 4, 6, 1,
       0, 6, 2, 2, 1, 4, 6, 2, 2, 1, 5, 0, 5, 4, 0, 5, 2, 4, 4, 2, 0, 0,
       5, 6, 1, 5, 2, 1, 0, 0, 3, 4, 3, 5, 4, 1, 6, 6, 4, 1, 6, 2, 5, 3,
       6, 0, 5, 3, 6, 3, 0, 1, 4, 0, 2, 4, 5, 3, 6, 2, 3, 2, 4, 2, 4, 3,
       4, 5, 0, 2, 2, 6, 6, 1, 0, 5, 0, 4, 3, 6, 3, 4, 3, 6, 1, 6, 1, 6,
       6, 4, 3, 6, 0, 0, 3, 1, 4, 1, 4, 4, 5, 6, 1, 0, 3, 0, 6, 3, 4, 4,
       5, 5, 6, 2, 4, 3, 5, 1, 2, 1, 5, 3, 5, 6, 1, 4, 5, 3, 0, 0, 6, 5,
       0, 6, 3, 1, 5, 6, 3, 5, 6, 2, 0, 1, 3, 1, 3, 4, 5, 4, 2, 6, 3, 6,
       3, 2, 2, 5, 2, 0, 6, 6, 4, 0, 4, 5, 3, 2, 5, 3, 4, 6, 6, 5, 3, 2,
       1, 6, 0, 2, 3, 4, 0, 3, 2, 2, 2, 3, 0, 3, 4, 1, 1, 4, 5, 1, 0, 4,
       0, 2, 4, 3, 2, 3, 4, 0, 2, 2, 2, 4, 3, 2, 4, 4, 5, 6, 5, 4, 5, 6,
       2, 4, 3, 1, 0, 1, 3, 0, 0, 3, 5, 5, 2, 1, 4, 3, 3, 1, 0, 3, 4, 0,
       2, 2, 6, 0, 2, 3, 1, 2, 4, 2, 2, 2, 1, 1, 6, 6, 0, 0, 0, 0, 6, 4,
       1, 3, 5, 4, 0, 1, 3, 3, 2, 5, 2, 1, 4, 3, 2, 1, 3, 2, 5, 6, 2, 1,
       5, 6, 3, 6, 4, 4, 2, 6, 0, 6, 1, 1, 6, 2, 5, 3, 6, 3])

In [22]:
from sklearn.metrics import classification_report, confusion_matrix

In [23]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        82
           1       0.91      0.88      0.90        85
           2       0.96      0.94      0.95       105
           3       1.00      0.98      0.99        95
           4       0.99      1.00      0.99        94
           5       0.87      0.95      0.91        87
           6       0.90      0.88      0.89        86

    accuracy                           0.94       634
   macro avg       0.94      0.94      0.94       634
weighted avg       0.94      0.94      0.94       634

In [31]:
print(classification_report(ytest,yrandompredict))

              precision    recall  f1-score   support

           0       0.97      0.95      0.96        82
           1       0.88      0.92      0.90        85
           2       0.96      0.95      0.96       105
           3       1.00      1.00      1.00        95
           4       1.00      1.00      1.00        94
           5       0.94      0.89      0.91        87
           6       0.88      0.92      0.90        86

    accuracy                           0.95       634
   macro avg       0.95      0.95      0.95       634
weighted avg       0.95      0.95      0.95       634

In [24]:
confusion_matrix(ytest,ypred)

array([[77,  5,  0,  0,  0,  0,  0],
       [ 5, 75,  0,  0,  0,  5,  0],
       [ 0,  0, 99,  0,  0,  0,  6],
       [ 0,  0,  0, 93,  1,  0,  1],
       [ 0,  0,  0,  0, 94,  0,  0],
       [ 0,  2,  1,  0,  0, 83,  1],
       [ 0,  0,  3,  0,  0,  7, 76]])

In [32]:
confusion_matrix(ytest,yrandompredict)

array([[ 78,   4,   0,   0,   0,   0,   0],
       [  2,  78,   0,   0,   0,   4,   1],
       [  0,   1, 100,   0,   0,   0,   4],
       [  0,   0,   0,  95,   0,   0,   0],
       [  0,   0,   0,   0,  94,   0,   0],
       [  0,   4,   0,   0,   0,  77,   6],
       [  0,   2,   4,   0,   0,   1,  79]])